### ISSUE TITLE
Support for WebSockets

### ISSUE THREAD

**Issue by sjennison** [SquidDev-CC/CC-Tweaks#107]
It may be outside the scope of this mod, but adding HTTP API support for WebSockets would be really awesome.

**Comment by SquidDev** [comment]
CCTweaks currently provided a TCP socket system (modelled off OpenComputer's version). I've had a look at the [WebSocket spec](https://tools.ietf.org/html/rfc6455) and it doesn't look too hard to implement - it is built on top of TCP. I might have a go myself.

My general approach is to not add a feature unless it is impossible or very impractical to implement Lua. WebSockets fall into this category.

**Comment by SquidDev** [comment]
That being said, using TLS/SSL would be hard so I might end up adding a TLS socket.

**Comment by sjennison** [comment]
Ah, I wasn't aware you added TCP sockets - I'm kinda new to CCTweaks. That's good to know and should indeed help a lot.

Thanks for taking a look :)

**Comment by SquidDev** [comment]
Yeah, CCTweaks is rather sparsely documented which is a problem I've been avoiding for a while.

If you have any other suggestions or bug reports please report them.
