### ISSUE TITLE
[1.8.9] ToolHostPlayer is not registered with Forge's EntityRegistry

### ISSUE THREAD

**Issue by Aaron1011** [SquidDev-CC/CC-Tweaks#112]
This is causing issues with [SpongeForge](https://github.com/SpongePowered/SpongeForge), which uses entity registration information for things like [Aikar's Timings](https://timings.aikar.co/v2/).

**Comment by SquidDev** [comment]
Are you sure this resolves the issue? It doesn't look like Forge's `FakePlayer` is registered with `EntityRegistry` either.

**Comment by Aaron1011** [comment]
@SquidDev: While technically `FakePlayer` should be registered too, we're able to special-case it since we know it will always exist (in Forge). Unregistered mod-added entities, however, prevent us from being able to accurately report details in Timings, without guessing at the mod id.

**Comment by SquidDev** [comment]
I've pushed a commit which hopefully fixes this, I'm slightly confused though: `ToolHostPlayer` extends `FakePlayer` so would it not be caught by the `FakePlayer` handler? I haven't looked through Sponge/Timing's code in great detail so don't know.

**Comment by Aaron1011** [comment]
@SquidDev: The registration is done against the class, so handling the superclass won't catch it. Additionally, it allows us to provide a more specific breakdown in Timings (e.g. grouping entities by the owning mod).
