### ISSUE TITLE
Cobalt multithreading does not appear to work

### ISSUE THREAD

**Issue by inklit** [SquidDev-CC/CC-Tweaks#121]
I set the thread count to 8, and then put 12 PCs directly next to eachother and ran your script that was posted on the CC forums:

```
print("Preparing to run a long task")
print("We're not going to yield much")

while true do
  for i = 1, 5 do
    for _ = 1, 2e6 do bit.band(1, 1) end
    print("Iteration " .. i)
  end
  write("Yielding... ")
  os.queueEvent("a")
  os.pullEvent("a")
  print("Done!")
end
```

All 12 PCs freeze when it isnt yielding, and so does every other computer on the server.

Do note that this is a public server with over 100 concurrent computers so I reckon my test size might not be enough but it still doesn't look very good for the case.

**Comment by SquidDev** [comment]
Yeah, I've had reports of this elsewhere too. I'll have a look into it: currently trying to figure out why Cobalt is borked.
