### ISSUE TITLE
Coroutine Sampler

### ISSUE THREAD

**Issue by inklit** [SquidDev-CC/CC-Tweaks#123]
I was thinking that this would be an incredibly useful feature.

A coroutine sampler that would be able to find out what computers are not yielding and causing CC lag.

**Comment by inklit** [comment]
Many players on my server are not very good programmers and frequently cause CC lag of incredible proportions. I am currently stuck using the default runtime though since Cobalt is broken in 1.2.0 and I am still waiting a version that has multithreading working well (#122). 

This would be less required with Cobalt/Rembulan and multithreading however I still think it should support both the default runtime and Cobalt/Rembulan.

Just thought I'd give some insight on why I requested this.

**Comment by SquidDev** [comment]
Migrated to SquidDev-CC/CCTweaks-Lua#12
