### ISSUE TITLE
Milking cows not working in 1.10

### ISSUE THREAD

**Issue by GabbeV** [SquidDev-CC/CC-Tweaks#128]
Using turtle.place() with a bucket in the selected slot used to milk cows in front of the turtle. This don't work in 1.10

**Comment by SquidDev** [comment]
I'd presume this is a CC but but I'll have a look at fixing it in unborked.

**Comment by SquidDev** [comment]
Fixed in the latest version of Unborked. Should be released in the next couple of days.
