### ISSUE TITLE
Attempt to clear label results in NullPointerException

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/CC-Tweaks#131]
issue:
When I try to clear the label of my computer I get a java nullpointerexception, and it doesn't clear the label.
To recreate:
1: place down a computer
2: label it something
3: attempt to clear it
4: java denies you

**Comment by SquidDev** [comment]
This was fixed in CCTweaks-Lua 1.2.4, just has not been released yet.

**Comment by hugeblank** [comment]
ah, thank you!
