### ISSUE TITLE
Turtles duplicating blocks when anti-grief plugin is installed

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/CC-Tweaks#133]
The issue:
On one of my servers I have a plugin installed called [RedProtect](https://forums.spongepowered.org/t/shield-anti-grief-redprotect-1-8-9-1-10-2/11846). It's typically a reliable plugin, but not when CC is installed. the turtle breaks the block, specifically the border fence around the plot, and effectively duplicates it. I've contacted the plugin author as well as you to see if maybe some sort of compromise can get worked out.
To recreate:
Steps to recreate:
1: load up a world with CC, Sponge, and the plugin RedProtect.
2: make a claim with fences. ('/rp tut' for info on how to do that)
3: get a mining turtle, and place it down facing into the fences
4: have the turtle attempt to break the fence
5: the turtle will break the fence and get it in its inventory, but the fence will reappear where it was.

**Comment by SquidDev** [comment]
- Minecraft version?
 - CCTweaks version?
 - ComputerCraft version?
 - Sponge version?
 - Logs?
 - There should be a config option called `turtlesObeyBlockProtection` in `ComputerCraft.cfg`, have you enabled that?

SwitchCraft ran ComputerCraft 1.79 (and now 1.80pr0) with GriefPrevention without encountering any issues, so I'd presume this is an issue with RedProtect, though I don't know for sure.

**Comment by SquidDev** [comment]
Right. From a brief trawl through the code, it appears RedProtect doesn't listen to the `ChangeBlockEvent.Pre` event, which is what is used to determine whether a block can be broken or not.

**Comment by hugeblank** [comment]
Oh boy, so this is redprotect, not CC
And I used griefprevention, it does not work at all. untrusted players were able to destroy and place blocks, and interact with inventories inside my claim.

**Comment by SquidDev** [comment]
> And I used griefprevention, it does not work at all. untrusted players were able to destroy and place blocks, and interact with inventories inside my claim.

Strange. It works fine on both my local testing server an SwitchCraft so I suspect this is a configuration issue somewhere.

**Comment by hugeblank** [comment]
Yeah, I haven't had any issues with Griefprevention until this server was set up. I'll check that turtlesObeyBlockPortection config option, but it should be setup as true.
EDIT: my assumption was right.

**Comment by inklit** [comment]
Contact bloodmc at Sponge to deal with GriefPrevention issues.
This issue is not CC's problem. CC works just fine with Sponge protection plugins assuming that they implement it correctly. GriefPrevention is the only plugin that has implemented it correctly.
https://github.com/MinecraftPortCentral/GriefPrevention

**Comment by hugeblank** [comment]
Yeah I'm convinced it's something wrong on my end. I'm going to do further testing before I go and nag at blood for something that could not even be his fault.

**Comment by SquidDev** [comment]
Closing as this isn't a bug with ComputerCraft/CCTweaks.

**Comment by hugeblank** [comment]
fair nuff :P

**Comment by SquidDev** [comment]
Don't worry, I'd rather people report bugs and they aren't on my end than not reporting them and it turning out to be critical 😄. Hopefully you can get this all sorted out, its just there isn't anything more I can do from a CC perspective.

**Comment by hugeblank** [comment]
Thank's for the help anyways! 

I think I'll hold off on using redprotect for now, griefprevention seems more reliable.

However I've done a few more tests with griefprevention, and my results... inconclusive. Either it works too well, by not allowing people to enter or exit the claim, even those who are trusted... Or not at all, in that all players are able to come in and raid my loots and plunder my base. I think now is a better time than ever to report the issue. :P
