### ISSUE TITLE
Did you ban access to local IP's?

### ISSUE THREAD

**Issue by birbe** [SquidDev-CC/CC-Tweaks#134]
That's a huge security risk if you haven't banned local access in the sockets implementation for CCTweaks...

**Comment by SquidDev** [comment]
Yes. [There is a config option](https://github.com/SquidDev-CC/CCTweaks-Lua/wiki/socket-library#configuration) should you need to test with a local machine. Please consult the documentation before coming here as it means you'll get a faster response time and less work for both of us 😄.
