### ISSUE TITLE
[1.11.2] Turtles cause random crash

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/CC-Tweaks#143]
[crash-2017-02-12_07.25.54-server.txt](https://github.com/SquidDev-CC/CCTweaks/files/769140/crash-2017-02-12_07.25.54-server.txt)
This was on KrakenKraft... and most all issues I have will be on there. 

From what I can gather from the log, an update 'animation' is playing, and the server just crashes.

**Comment by hugeblank** [comment]
It also should be noted that the label and the files the turtle had were removed in the process of this crash

**Comment by roger109z** [comment]
It seems to happen when the turtle tries to move to a block that is occupied by the player

**Comment by hugeblank** [comment]
^roger wants to remove that comment, so until he does, I'll leave this here :P

**Comment by SquidDev** [comment]
Fixed in Unborked 1.1.2
