### ISSUE TITLE
[1.11.2] Turtle movement causing crash

### ISSUE THREAD

**Issue by hugeblank** [SquidDev-CC/CC-Tweaks#144]
[crash-2017-02-12_07.54.13-server.txt](https://github.com/SquidDev-CC/CCTweaks/files/769153/crash-2017-02-12_07.54.13-server.txt)
Yet another crash, but this time it is executing a movement.
Roger claims it ran into him, and promptly crashed.

**Comment by SquidDev** [comment]
Fixed in Unborked 1.1.2
