### ISSUE TITLE
1.8.9-1.3.0 - rednet.open("back") clears screen on advanced wireless pocket computers

### ISSUE THREAD

**Issue by HydrantHunter** [SquidDev-CC/CC-Tweaks#145]
Just installed MC 1.8.9 with CC 1.79 and a few other mods (including CC Tweaks 1.8.9-1.3.0) - using Forge 1.8.9-11.15.1.1902 via MultiMC; and I'm having a problem with rednet.open("back") on advanced wireless pocket computers (I haven't tested it on other CC computers or versions yet).

With CC Tweaks loaded, if the modem is closed and I call rednet.open("back") the modem opens fine, but the screen clears as well.  With CC Tweaks not loaded, the screen isn't cleared.  I noticed this because I have a script that updates the screen as it loads; and when it opens the modem the progress update disappears.

This is easily repeatable for me so if it's a valid issue and you need a specific log file or other information, I'm happy to provide it.  Here's the [fml-client-latest.log](http://pastebin.com/PRVY8fg8) in case it's of value.

EDIT: I've tested this on advanced computers and they don't appear to be affected.  Also, calling rednet.close("back") on an open modem (on an advanced wireless pocket computer) clears the screen as well.

Additionally, in the Lua prompt, after the screen is cleared (either due to an open or close call), the screen is restored if you press enter or start to type again.

**Comment by SquidDev** [comment]
This is occurring because the computer state is changing but we are not sending terminal state, resulting in it being cleared. We can probably change [this line](https://github.com/SquidDev-CC/CCTweaks/blob/minecraft-1.8.9/src/main/java/org/squiddev/cctweaks/core/patch/ServerComputer_Patch.java#L181) to be sent all the time.

**Comment by SquidDev** [comment]
A temporary solution til then would be to disable `Packets.terminalLimiting` in the config.

**Comment by HydrantHunter** [comment]
Thanks for the quick reply, the explanation, and the workaround!
