### ISSUE TITLE
ccTweaks 1.8.9-1.3.1 - Key repeat not working with ccTweaks loaded

### ISSUE THREAD

**Issue by HydrantHunter** [SquidDev-CC/CC-Tweaks#147]
Not much to add - holding down a key doesn't result in key repeat kicking in while ccTweaks is loaded.  Loading the same map without ccTweaks allows key repeat to function normally.

MC 1.8.9
CC 1.79
ccTweaks 1.8.9-1.3.1
Forge 11.15.1.1902

Not sure what other info to include - let me know if you require anything else.

EDIT:  After being plagued by this issue for more than a week and narrowing it down to ccTweaks, the problem seems to have resolved itself.  I just reloaded the map *with* ccTweaks and key repeat is working fine.  Since I can no longer replicate this issue I'm closing it.

**Comment by SquidDev** [comment]
I've encountered the same issue a couple of times, though I don't think it is CCTweaks' fault: I don't touch the GUI code. Were you by any chance running JEI? - I think the 1.8.9 versions mess with key repeats.

**Comment by HydrantHunter** [comment]
I am, in fact, running JEI with the map in question.  If the problem returns, I'll turn my eye toward JEI.  Thank you...again.

**Comment by SquidDev** [comment]
Also worth noting that I've only experienced this on 1.8.9. Comparing the [1.8.9](https://github.com/mezz/JustEnoughItems/blob/1.8.9/src/main/java/mezz/jei/input/GuiTextFieldFilter.java#L99) and [1.10.2](https://github.com/mezz/JustEnoughItems/blob/1.10/src/main/java/mezz/jei/input/GuiTextFieldFilter.java#L100-L105) versions shows that this is almost certainly caused by JEI.

**Comment by SquidDev** [comment]
Reopening as it might be possible to fix this: see [this commit for Plethora](https://github.com/SquidDev-CC/plethora/commit/8fcd4197736b7047c8af8c95edf68e7bad142fa8).

**Comment by HydrantHunter** [comment]
Wow - you are all over this - thank you for making life in 1.8.9 a bit easier.

**Comment by SquidDev** [comment]
Would be a good idea if I actually reopened this 😦.
