### ISSUE TITLE
Computer vanishes on right click

### ISSUE THREAD

**Issue by JomerDev** [SquidDev-CC/CC-Tweaks#148]
MC 1.10.2
CC 1.80pr0
CCTweaks 1.3.1
Unborked 1.0.5

When I try to rightclick a advanced CC Computer it just vanishes. Once it also turned into the block I had in my hand (some wood) on a right click.

Log: https://hastebin.com/ecevaperek.vbs

**Comment by JomerDev** [comment]
After some more testing, it seems this only happens in Multiplayer, not in Singleplayer

**Comment by SquidDev** [comment]
Ugghr, what one earth? It says `BlockGeneric.getDefaultBlockState` isn't defined but it evidently is. 

Can you enable `testing.dumpAsm` in the CCTweaks config file, run it, and zip up the `asm/cctweaks` folder in the server directory.

I'm not sure that is the full server log: if possible, can you find the larger one - just so I can see version numbers, file names, etc... of other mods. Thanks.

**Comment by JomerDev** [comment]
https://puu.sh/ugvJZ/626ce50d03.zip 
Here is a zip with the cctweaks folder and all the logs I could find

Thank you for beeing so fast :D

**Comment by SquidDev** [comment]
Urrhgr. Right, I've been totally unable to reproduce. I'll do some more digging and see if methods are getting incorrectly (de)obfuscated or something. If this happens again (or is a routine occurrence), can you let me know.

Thanks, sorry about this all.

**Comment by JomerDev** [comment]
I'm sorry, but this is a routine occurrence. This did occur everytime I tried to right click a computer in multiplayer.
I can try and redownload computercraft and unborked again, in the hopes of it changing something, but I doubt it

**Comment by SquidDev** [comment]
Right, I will try to recreate again on my end. Would it be possible to try with just ComputerCraft and Unborked, (and then CCTweaks if it doesn't occur)? I doubt another mod is causing problems but I'd like to check.

Thanks.

**Comment by JomerDev** [comment]
I got the exact same error with only CC and unborked

Edit: But I could open the computer with only CC

**Comment by SquidDev** [comment]
Uggghr. I've, as far as I can tell, recreated your setup: Unborked 1.0.5, CC 1.80pr0 and MinecraftForge 12.18.3.2234, yet still cannot reproduce. Do you happen to know if `FTBserver-1.10.2-12.18.3.2234-universal.jar` is different to MinecraftForge's default server? 

If you haven't already (not sure if you created a fresh setup or not above), could you try with a fresh install of MinecraftForge?

Really sorry about this, this is really weird.

**Comment by JomerDev** [comment]
I will try it as soon as I have the time to do so

**Comment by SquidDev** [comment]
@Nathan1852 Have you had a chance to try this again?
