### ISSUE TITLE
[1.10.2] java.lang.NoSuchMethodError: dan200.computercraft.shared.computer.blocks.TileComputerBase.native_writeToNBT

### ISSUE THREAD

**Issue by lurr** [SquidDev-CC/CC-Tweaks#151]
Crash log: http://pastebin.com/8UUFupB0

Unborked 1.10.2-1.80pr0-1.0.5
CCTweaks 1.10.2-1.3.2

**Comment by SquidDev** [comment]
It is possible the NBT method mappings changed in 1.10.2, resulting in the correct method not being copied.
