### ISSUE TITLE
Error mounting lua/rom

### ISSUE THREAD

**Issue by Enclave2020** [SquidDev-CC/CC-Tweaks#152]
Sorry me for post in wrong section
I installed unborked-1.10.2-1.80pr0-1.0.5 and ComputerCraft1.80pr0. Single-player works fine.
In multiplayer I get error on all computers (include that just created)
"Error mounting lua/rom"
What I should do to fix this?

**Comment by SquidDev** [comment]
Hrrmm, weird. This is something I haven't seen before, suggesting a mod interaction issue or a corrupted ComputerCraft download. 

Can you first try a reinstall of ComputerCraft and, if that doesn't help, can you attach your logs and mod list (with version numbers)? Thanks.

**Comment by Enclave2020** [comment]
I removed server map and mods. Then redownloaded Unborked & CC. Still get same error. Here is log:
https://drive.google.com/file/d/0B_ETpLG891bzNGZ6SEdpY29QLUE/view?usp=drivesdk

**Comment by Enclave2020** [comment]
Fixed! All problem was in "!" in the server path. Sounds strange but it is

**Comment by SquidDev** [comment]
Ahhhh. That kinda makes sense: `!` is used in Java to separate the path to a `.jar` file and it's contents. This means CC was getting confused with `!` and looking outside it's `.jar` for the rom files. Thanks for clearing things up 😄, sorry I couldn't be of more help.
