### ISSUE TITLE
[1.10.2] _MC_VERSION and _HOST state incorrect Minecraft versions

### ISSUE THREAD

**Issue by lurr** [SquidDev-CC/CC-Tweaks#153]
CCTweaks: 1.3.1 (I'm sorry I'm outdated 😢)
Unborked: 1.0.5
MC: 1.10.2

As title describes.
Image [here](http://i.imgur.com/X2Grur5.png)

**Comment by SquidDev** [comment]
Should be fixed. Will appear whenever I next update Unborked and CCTweaks.
