### ISSUE TITLE
[1.10.2] java.lang.NullPointerException: Ticking block entity

### ISSUE THREAD

**Issue by lurr** [SquidDev-CC/CC-Tweaks#154]
Tested on:
CCTweaks 1.3.3
Unborked 1.0.5

Crash log [here](http://pastebin.com/DUj0RBPQ)

**Comment by SquidDev** [comment]
I'm not even sure how this happened. It is like the modem got unloaded but is still being ticked. Do you have any idea what was happening at the time, or did this just occur randomly?

**Comment by SquidDev** [comment]
I'm going to close this as I don't think it is a CCTweaks bug: the TE should never be ticked when the world is `null`.
