### ISSUE TITLE
CCTweaks 1.4.0 Server Side Crash (w/Plethora 1.1.4+)

### ISSUE THREAD

**Issue by Alaberti** [SquidDev-CC/CC-Tweaks#159]
https://pastebin.com/raw/XW3shPTX

I know the report says Plethora, but the crash does not happen with CCTweaks 1.3.3, just 1.4.0.

Tested on a dedicated server with Plethora 1.1.5 and 1.1.4 as well. Forge 2281.

**Comment by SquidDev** [comment]
What on earth? That class is definitely defined. Sorry about this, I'll take a look. 

Thanks for reporting!

**Comment by vico93** [comment]
Thanks @SquidDev !
