### ISSUE TITLE
Multipart peripherals

### ISSUE THREAD

**Issue by ElvishJerricco** [SquidDev-CC/CC-Tweaks#16]
Allow peripherals in the multipart. Cables detect all IPeripherals and also render in the direction of slotted ones. Needs to use ```getRenderBounds``` on the part to determine how far out to render the cable.

**Comment by SquidDev** [comment]
I'm still confused by this. We currently support [peripherals in other multiparts](https://github.com/SquidDev-CC/CC-Tweaks/blob/master/src/main/java/org/squiddev/cctweaks/core/integration/multipart/MultipartIntegration.java#L51-L69) but how would you connect to these peripherals inside the current multipart - the modem can't connect to something already inside it. I agree we need to fix the cable render bounds issue though.

**Comment by ElvishJerricco** [comment]
But I don't believe that we support multipart peripherals via cables in the same multipart. Like, I think we should support having multipart peripherals connected to the network just by the cables in the multipart.

**Comment by ElvishJerricco** [comment]
Ok. Classes are out now (finals done) so I should be able to start putting some focus back on this stuff.

**Comment by SquidDev** [comment]
Oh good! How did they go. Exams start in a week for me, so fun fun fun!

**Comment by ElvishJerricco** [comment]
Finals went fine. Good luck on your exams!

The issue is that all we support is delegation of INetworkNode methods from the center slot nodes to other multipart nodes. We don't support actually providing a multipart as an IPeripheral, unless that part implements INetworkNode, dummies all the methods, and returns itself (or an encapsulated peripheral object) to the visitor.

It'd be nice if a multipart could just implement IPeripheral, and if we had something similar to IPeripheralProvider for multiparts. This way you don't need to go through the hassle of all that boilerplate code for INetworkNode just to get your multipart as a peripheral.

**Comment by SquidDev** [comment]
Just going through the issues as 0.2 draws closer. Do you mean like [this provider[(https://github.com/SquidDev-CC/CC-Tweaks/blob/master/src/main/java/org/squiddev/cctweaks/integration/multipart/MultipartIntegration.java#L69-L88)? Currently we check to see if there is a multipart that occupies that side, and if so we return it, which is how `PartModem` is a peripheral. 

What this doesn't do is render the cables attaching to it.

**Comment by ElvishJerricco** [comment]
Nono. I mean like if you have a peripheral part in the block with a cable, that cable will add that peripheral part to the network.

**Comment by SquidDev** [comment]
Ahhhh - I understand. So we'd need to find local nodes and `getConnectedPeripherals` to return them. This does kinda go against current behaviour though - that you need a modem to connect to a peripheral. I'm fine with adding this though - though we'll need to fix rendering first.

**Comment by ElvishJerricco** [comment]
I think the issue is that how do you connect and disconnect these peripherals? And how does the player see what its ID is? Perhaps its best to leave these issues up to peripheral developers, and not have this feature built in?

**Comment by ElvishJerricco** [comment]
Considering my previous comment, I don't think there's a good way to implement this in CC-Tweaks. It's going to have to be left to the peripheral developers. But that's ok, because it's not too hard. Go ahead and reopen if you disagree.
