### ISSUE TITLE
[1.4.1] CCTweaks Pre-init crash (modem class missing?)

### ISSUE THREAD

**Issue by Alaberti** [SquidDev-CC/CC-Tweaks#161]
https://pastebin.com/LT75PqEE

CC Tweaks: 1.4.1
Plethora: 1.1.6
Computercraft: 1.80pr0-2017052315

As you can see, I'm using the latest (as of this post) dev build of CC. Is that relevant to this crash?

**Comment by SquidDev** [comment]
A lot of CCTweaks has been (or is in the process of) merged into "actual" ComputerCraft. This has resulted in the equivalent features in CCTweaks breaking (hence your crash here). As CC's code base is still in flux, I don't really want to make a release of CCTweaks - it is likely it would be broken again in a couple of days. 

In short, I'm not going to fix this now - I'm waiting for an official release of ComputerCraft before attempting anything.
