### ISSUE TITLE
[1.4.1] Personal Computer not working (non-crash issue)

### ISSUE THREAD

**Issue by Alaberti** [SquidDev-CC/CC-Tweaks#162]
https://pastebin.com/X6CKUcS1

I'm seeing this in the console on a dedicated server. The player says he can right click to access it and sees the CraftOS mark but can't do anything else (no user input). This is after updating to CCTweaks from 1.3.1 I believe - we are not using the dev computercraft builds as per your advice on them earlier. He also says a startup program he has might be the cause, but couldn't say.

Edit: startup program works. Better plan: @Abelatox GET IN HERE AND EXPLAIN YOURSELF.

**Comment by Abelatox** [comment]
Well bcaically now the Pocket Computer shows in had like a map and if I right click it starts and runs the startup program (if any) and tries to access.

**Comment by SquidDev** [comment]
Can I confirm you're running the latest version of Unborked (1.0.6 for Minecraft 1.10.2, 1.1.5 for Minecraft 1.11.2)?

**Comment by Alaberti** [comment]
Ah! 1.80pr0-1.0.5 is what I have. I wasn't even aware there was an update. Whoops

**Comment by SquidDev** [comment]
No worries, Unborked's distribution system isn't the best in the world :/. [You can download 1.0.6 here](https://dl.bintray.com/squiddev/maven/org/squiddev/unborked/1.10.2-1.80pr0-1.0.6/unborked-1.10.2-1.80pr0-1.0.6.jar). Sorry, that update fixed a couple of bugs, which in turn required some changes to CCTweaks.

**Comment by Abelatox** [comment]
Well basically now the Pocket Computer shows in had like a map and if I right click it starts and runs the startup program (if any) and tries to access.
