### ISSUE TITLE
Crash on load 

### ISSUE THREAD

**Issue by tripl3dogdare** [SquidDev-CC/CC-Tweaks#169]
I cannot launch my game, as it crashes immediately every time I try. The crash comes from Plethora Peripherals when that's enabled, but the crash is very similar and traces back alternately to a ComputerCraft package or a CCTweaks package. The game crashes without Plethora with the same error, although it seems to error on various different missing files with little to no pattern. I've attached the crash report below.

[crash-2017-07-13_19.10.29-client.txt](https://github.com/SquidDev-CC/CCTweaks/files/1147060/crash-2017-07-13_19.10.29-client.txt)

**Comment by SquidDev** [comment]
Ahhh, sorry about this - it isn't super clear. The latest betas of Plethora and CCTweaks require development builds of ComputerCraft, which haven't been put on CurseForge yet. These can be found [here](http://cc.crzd.me), namely [this file](https://cc.crzd.me/maven/dan200/computercraft/ComputerCraft/1.80pr0-build10/ComputerCraft-1.80pr0-build10.jar).

**Comment by tripl3dogdare** [comment]
Thank you! That appears to work ^-^
