### ISSUE TITLE
Give peripherals network access

### ISSUE THREAD

**Issue by ElvishJerricco** [SquidDev-CC/CC-Tweaks#17]
When attached to a computer, provide that peripheral that computer's network until it becomes detached.

Perhaps an interface that extends IPeripheral and adds
```java
void attachToNetwork(INetworkedComputerAccess computer);
```
Where INetworkedComputerAccess is extends IComputerAccess, and adds
```java
Map<String, IPeripheral> getAttachedPeripherals();
```

---

Alternatively, we could add peripheral attachment handling API, where you can register handlers to do custom behavior on peripheral attach / detach. We could use this to check if peripherals implement an INetworkedPeripheral interface similar to the one outlined for the first suggestion.

**Comment by SquidDev** [comment]
I think both would be useful, though I'm not sure how the second one would be used by the user - how would the peripheral get access to the network if it doesn't implement some sort of networking API?

I would love to add a  `pushToPeripheral` method to [OpenPeripheral inventories](https://github.com/OpenMods/OpenPeripheral-Integration/blob/master/src/main/java/openperipheral/integration/vanilla/AdapterWorldInventory.java), which would require a custom provider, but I'm not sure how the `IPeripheralAdapter` would access the network.

**Comment by ElvishJerricco** [comment]
The idea behind the second one would be that we use our own API to register handling of networked peripherals.

```java
registerPeripheralAttachmentHandler(new IPeripheralAttachmentHandler() {
    private Map<IComputerAccess, INetworkedComputerAccess> accessMap = new HashMap<IComputerAccess, INetworkedComputerAccess>();


    @Override
    public void attach(IPeripheral p, IComputerAccess c) {
        if (p instanceof INetworkedPeripheral) {
            INetworkedPeripheral n = (INetworkedPeripheral) p;
            INetworkedComputerAccess access = new NetworkedComputerAccess_Impl(c);
            accessMap.put(c, access);
            n.attachToNetwork(access);
        }
    }

    @Override
    public void detach(IPeripheral p, IComputerAccess c) {
        if (p instanceof INetworkedPeripheral) {
            INetworkedPeripheral n = (INetworkedPeripheral) p;
            INetworkedComputerAccess access = accessMap.remove(c);
            n.detachFromNetwork(access);
        }
    }
});
```

**Comment by ElvishJerricco** [comment]
So I've been looking at this for a bit now, and I'm having a touch of trouble. Issue is, IComputerAccess isn't exactly enough. The object passed needs to give the handler access to the entire peripheral network.

What object should I be trying to pass instead of IComputerAccess, and how should I be getting that object?

**Comment by ElvishJerricco** [comment]
Here's an idea, maybe something closer to the ```BasicModem``` class? Slightly more abstract though, as it also needs to support giving an object to represent the computer as its own network when a peripheral is attached directly to it.

**Comment by ElvishJerricco** [comment]
After derping about with the ideas I've mentioned, I realized they're not exactly coherent. The idea of a peripheral attachment handling API is counter to the idea that a peripheral's network access should be independent of its computer access. The peripheral attachment handling API suggested that the two be invoked in the same manor, but they're fundamentally different services, that are supposed to be invoked at different times.

Computer access is handled when connected to a new computer. Network access is handled when connected to a network. A peripheral can be attached to a single network, and consequently be attached to multiple computers. Or a peripheral can be attached to a single network with no computers at all.

So. After deleting much incoherent code, I think I finally have a solid plan for this. When a modem attaches or detaches its peripheral to the network, it will then call the INetworkAccess attach or detach method on the peripheral. No API abstraction. Just easy code.

**Comment by SquidDev** [comment]
I think that makes more sense - and it means we don't need to worry about rewriting `IPeripheral.attach`. I presume we would still have a custom `INetworkedPeripheral` interface though, and a custom way of providing them?

One potential issue is that [peripheral proxies](https://github.com/OpenMods/OpenPeripheral-Addons/blob/master/src/main/java/openperipheral/addons/peripheralproxy/TileEntityPeripheralProxy.java#L55) wrap the peripheral in a wrapper, so we would need a custom provider to work with this.

**Comment by ElvishJerricco** [comment]
I suppose peripheral proxies could just implement ```INetworkedPeripheral```, and delegate to the proxied peripheral if it is an ```INetworkedPeripheral```?

**Comment by SquidDev** [comment]
Normally yes, but I don't think OpenPeripherals will add that. CCTweaks isn't a large enough mod for them to add support for it. I don't see any harm in additional providers - there is some other stuff I might like to try with OP integration. I know 99% of the time we wouldn't want it. 

It would probably be a provider that runs off `IPeripheral`s rather than using the same signature as the normal peripheral provider. It is more of a nice to have feature than a necessity though.

**Comment by ElvishJerricco** [comment]
Oh duh. How would a provider be capable of this? Wouldn't it make more sense to do some ASM hacking to implement INetworkedPeripheral on their peripheral proxies?

**Comment by SquidDev** [comment]
ASM was at the back of my mind whilst writing my previous comment. What I would love is an interface OP adapters can implement that allows them to use network access, but looking at it I'm not sure how possible that is.

I'm not sure I like either method. ASM seems hacky, and I'm not sure how a provider would work - what would the provider then call to get the peripheral to respond? My natural response would be "add providers to all the things!", though I'm not sure that is appropriate.

ASM is probably the best way to go then. I guess we can switch to a provider if we find we really need to.

**Comment by ElvishJerricco** [comment]
I'm honestly surprised that the peripheral proxy tile even acts as an IPeripheral. I would have expected that the peripheral provider for it just deflects to the block its pointing at, rather than actually implementing a proxy object. Unfortunate that it doesn't just deflect. Then we wouldn't have to do anything at all

**Comment by ElvishJerricco** [comment]
Also, the fact that it doesn't deflect means we can never fully support it. If a peripheral is accessing other peripherals on the network, it might be checking if some peripherals are instances of certain interfaces and such. The peripheral proxy doesn't implement whatever interfaces the user decides to make use of, and we can't provide a way to make it implement that.

**Comment by SquidDev** [comment]
I think the PeripheralProxy doesn't just return the peripheral is because it needs to support the peripheral changing - which isn't supported very well by default - with vanilla CC breaking a modem didn't even remove the peripheral in my testing.

I think I nicer way would be to provide a custom `IPeripheralProxy` interface which we inject into the peripheral proxy - and other people could use if they implement one. This means custom `INetworkedPeipherals` could check do: 

```java
if(periph instanceof IPeripheralProxy) {
  periph = ((IPeripheralProxy)periph).getPeripheral());
}
```

I'm wondering if we also want an `ITargetedPeripheral` interface - a peripheral that isn't a tile entity instance but is targeted at one (such as OpenPeripheral's [`AdapterPeripheral`](https://github.com/OpenMods/OpenPeripheral/blob/master/src/main/java/openperipheral/interfaces/cc/wrappers/AdapterPeripheral.java)). I guess we might want a custom helper method of `getBasePeripheral` which does something like:

```java
while(periph instanceof IPeripheralProxy) {
  periph = ((IPeripheralProxy)periph).getPeripheral());
}
return periph;
```

as you could technically chain peripheral proxies together and we aught to support that.
