### ISSUE TITLE
[Suggestion] Add limit to biginteger.newProbPrime()

### ISSUE THREAD

**Issue by lurr** [SquidDev-CC/CC-Tweaks#171]
Leaving it at high values can slow down a server when people find primes.
A cap of ~2048 by default would be sufficient, and a config option to change this would probably also be desired.

**Comment by SquidDev** [comment]
Closed in SquidDev-CC/CCTweaks-Lua@43b1bc0c9967b0f197afd13269f76fd42bd7ef0c.
