### ISSUE TITLE
[1.11.2] Crash with latest CCTweaks and ComputerCraft

### ISSUE THREAD

**Issue by Tencao** [SquidDev-CC/CC-Tweaks#175]
Since you're maintaining the current computercraft, I feel it's best to post this crash report here as I don't know which mod causes it.

https://paste.ee/p/1qO7u

Forge version - 13.20.1.2393
CCTweaks - 1.5.0-pr0
ComputerCraft - 1.80pr0-build15

**Comment by Bluexin** [comment]
So uhh, I fail to see how this was resolved.
Was closing the issue a missclick? @SquidDev

**Comment by SquidDev** [comment]
@Bluexin No. aee87ed943daa59606fa6e6a5fd6157a63c5ef0b should have fixed this (namely bumping the CCTweaks-Lua version to include SquidDev-CC/CCTweaks-Lua@2a540165d5e6e55673bec66a3526a16d02d1f5ac).

Can you confirm you're on the latest version (pr1) and the crash is the same? If so, can you post your logs - it's possible something only works in my dev environment but not in an obfuscated one.

**Comment by Tencao** [comment]
https://hastebin.com/ilazuveneb.pas
Same crash, latest version

**Comment by SquidDev** [comment]
Can you try [using this jar](https://www.dropbox.com/s/e5xnq76bbk3vh9y/CCTweaks-1.10.2-1.5.0-pr1-bug175.jar?dl=1) and see if that works? It appears my 1.12 compat patches were breaking things in a normal install.

**Comment by Tencao** [comment]
https://paste.ee/p/dth2a
Wrong minecraft version error

**Comment by SquidDev** [comment]
Ahhh, sorry. I've had someone on 1.10.2 with the same issue and lost track of who was who. [This'll work for 1.11.2](https://www.dropbox.com/s/5jsgnqaozx22e9s/CCTweaks-1.11.2-1.5.0-pr1-bug175.jar?dl=1).

**Comment by Bluexin** [comment]
Sorry for the delay on getting back, we had other issues too.
The crash doesn't happen anymore with the latest version you provided, thanks :)
