### ISSUE TITLE
crash when computer block is clicked

### ISSUE THREAD

**Issue by Grizzord** [SquidDev-CC/CC-Tweaks#176]
the game loads but then when i try to access the computer the game crashes. .
[crash-2017-08-31_13.41.12-client.txt](https://github.com/SquidDev-CC/CCTweaks/files/1268168/crash-2017-08-31_13.41.12-client.txt)

**Comment by SquidDev** [comment]
Can you try [using this jar](https://www.dropbox.com/s/e5xnq76bbk3vh9y/CCTweaks-1.10.2-1.5.0-pr1-bug175.jar?dl=1) and see if that works? It appears my 1.12 compat patches were breaking things in a normal install.

**Comment by Grizzord** [comment]
that fixed it.
