### ISSUE TITLE
Disconnect cables with wrench

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaks#19]
Add the ability to disconnect multipart cables with buildwraft wrenches. We could store this in another flag and merge the two when checking `canBeVisited` and `canVisitTo`.

**Comment by ElvishJerricco** [comment]
I like the idea, but then the cable has to be a multipart cable to use this feature, which can be frustrating when you want to use it on a non-multipart cable.

**Comment by SquidDev** [comment]
I know, we could add a custom handler to the activate method to convert it to a multipart block - but this seems less than ideal. The alternative would be an 'advanced cable' which has more functionality but I feel we would have to make it really worthwhile for it to exist.

**Comment by ElvishJerricco** [comment]
That's an interesting idea. I dunno though...

**Comment by SquidDev** [comment]
An alternative would be to dye cables instead - so different coloured cables cannot connect to each other.

**Comment by SquidDev** [comment]
The most sensible thing to do seems to be to add a `IColoredNode` or something which controls if a connection should occur. That can probably wait until 0.2.1 though.

**Comment by ElvishJerricco** [comment]
Yea I'd say we hold onto this one until 0.2.1.

**Comment by SquidDev** [comment]
I've thought about this a lot and I'm not sure I see the point in this: I can't see any benefit of being able to separate networks. It would be a really cool feature to add but I don't want to add a load of unneeded complexity.

I might open if someone can think of an application of this: separating cables without FMP installed would be good.
