### ISSUE TITLE
loadstring cant load byte code

### ISSUE THREAD

**Issue by HDeffo** [SquidDev-CC/CC-Tweaks#37]
trying to load lua bytecode will result in a null pointer error. The below example would work in vanilla computercraft:

loadstring(string.dump(print))

**Comment by SquidDev** [comment]
Hmmm, I thought I'd tested this working. I'll have a test on the latest build.

**Comment by SquidDev** [comment]
Ahh. `string.dump` trims line numbers, so it tries to index items out of the array's bounds.

**Comment by SquidDev** [comment]
Merged changes as of 1ec8e7a6b818daae2097733ebdad64546986c6c6.

I don't know when the next official version will be released so you can [grab a pre-release](http://maven.bonzodandd.co.uk/org/squiddev/CCTweaks/1.7.10-0.2-pr1/CCTweaks-1.7.10-0.2-pr1.jar), though note that it is pretty unstable so you may want to back up everything first.

Thanks for reporting this!
