### ISSUE TITLE
Crash with Ender IO

### ISSUE THREAD

**Issue by toarii** [SquidDev-CC/CC-Tweaks#38]
Hi,

My server crash when I launch with CC-Tweak, and when I remove, the server work fine.
My crash log : http://pastebin.com/z2rWFBGS

Thnaks.

**Comment by SquidDev** [comment]
Seems to be a server only issue.

**Comment by SquidDev** [comment]
I can't reproduce on a fresh install of EnderIO 2.2.8.381 and CCTweaks 1.4.2. 

I'm no longer packaging the CofH API in 0.2 so you might want to [grab a pre-release](http://maven.bonzodandd.co.uk/org/squiddev/CCTweaks/1.7.10-0.2-pr1/CCTweaks-1.7.10-0.2-pr1.jar), though note that it is pretty unstable so you may want to back up everything first. 

Alternatively if you open the CCTweaks .jar file and delete the `cofh` folder it should work.

**Comment by toarii** [comment]
I have try to with another server and there is no error with the same mods and configs. Sorry for that, I will search what is the problem.
