### ISSUE TITLE
0.3 and beyond

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaks#39]
Series of features I'm considering adding, not all may make themselves into versions

## ~~Profiler (Previously mentioned in #8 )~~ - Not possible with LuaJ 2
I've written a very basic profiler for CC. It would be great to expand this and integrate it with the debug wand.

## ~~Pocket computer notify (In #3)~~ - Will revisit one day
As mentioned in [this thread](http://www.computercraft.info/forums2/index.php?/topic/21910-pocket-computer-ring-or-push-notification/). Not sure how it would look but could be cool.

## HTTP/Socket extensions (Implemented in 056d97c0fae98194807a726eed2924fc752ba9df)
Mixture of [OpenComputer's socket API](http://ocdoc.cil.li/api:internet) and [this topic](http://www.computercraft.info/forums2/index.php?/topic/22883-http-enhancements/). The issue with this is that scripts cannot rely on this existing so not sure it would get widespread use.

## Turtle tool host (~~[`feature/tool-host`](https://github.com/SquidDev-CC/CC-Tweaks/tree/feature/tool-host)~~ Merged with #47)
Said this before, probably deleted the issue. Instead of the tool host providing an inventory slot though - it could just use the active slot of the turtle. 

I'd probably have to add custom support for Bows and other tools that require right click.

This might be better implemented in a mod such as [Peripherals++](https://github.com/austinv11/PeripheralsPlusPlus) instead.

## ~~Turtle wand (#65)~~ - Nah. See the issue for reasons why.
I've always liked the idea of using Turtle labels to convey information to the player. In CC 1.6.0, turtle names were displayed even when not hovering over. The turtle wand could implement similar rendering functionality to Ender IO's 'Staff of Travelling' - drawing turtles larger than they are, through walls, with their label shown. Probably at the same time as I do #9.

**Comment by SquidDev** [comment]
I got something working:
![](http://i.imgur.com/Lpa8IBw.png?1)

**Comment by Nathan1852** [comment]
I would love to see the Pocket computer notify as well as a socket Api which resembles OCs Api (especially the TCP socket ;) )
I think the 'issue' that scripts can not rely on this existing isn't that bad, since CC has the http api and the pastebin program which noone can rely on either, since they can be disabled in the configs.
I just wanted to give my two cents to this update, which I will look forward to

**Comment by SquidDev** [comment]
Implemented socket/TCP API in 056d97c0fae98194807a726eed2924fc752ba9df. I'd love to implement a pocket computer notification system, but I'm not sure of the best look for it. Thoughts/feedback welcome.
