### ISSUE TITLE
Error with the new beta

### ISSUE THREAD

**Issue by Nathan1852** [SquidDev-CC/CC-Tweaks#43]
I've downloaded the new version to use the fix for the turtle.refuel() with RF.
Sadly I crashed when I tried to join a world with already existing CC Lan cables.

The Error:
[Error] Encountered an unexpected exceptionnet.minecraft.util.ReportedException: Ticking block entity	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]Caused by: java.lang.NoSuchMethodError: net.minecraft.world.IBlockAccess.func_72800_K()I	at org.squiddev.cctweaks.core.network.visitor.SearchLoc.getNode(SearchLoc.java:43) ~[SearchLoc.class:?]	at org.squiddev.cctweaks.core.network.visitor.NetworkVisitorIterator.enqueue(NetworkVisitorIterator.java:65) ~[NetworkVisitorIterator.class:?]	at org.squiddev.cctweaks.core.network.visitor.NetworkVisitorIterable.iterator(NetworkVisitorIterable.java:51) ~[NetworkVisitorIterable.class:?]	at dan200.computercraft.shared.peripheral.modem.TileCable.findPeripherals(TileCable.java:177) ~[TileCable.class:?]	at dan200.computercraft.shared.peripheral.modem.TileCable.func_145845_h(TileCable.java:659) ~[TileCable.class:?]	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]

**Comment by SquidDev** [comment]
`IBlockAccess.getHeight` doesn't exist. Slightly strange. I'll test.

**Comment by Nathan1852** [comment]
Meanwhile it should be possible to load the world with the old version, remove all the cables and replace them after loading the world with the new version, right?

**Comment by SquidDev** [comment]
I don't think so, I'm pretty sure that this is an issue with all cables - new or old versions as they are the same TileEntity.

**Comment by SquidDev** [comment]
If you can redownload and test again. I haven't tested on a server but it should all work.

**Comment by Nathan1852** [comment]
Thak you for the fast fix. I will try it

**Comment by SquidDev** [comment]
Sorry, [this one](http://maven.bonzodandd.co.uk/org/squiddev/CCTweaks/1.7.10-0.2-pr1/CCTweaks-1.7.10-0.2-pr1.jar). The others are deobf versions, API jar, sources and javadoc. I'll put it on Curse Forge once 0.2 is officially released.
