### ISSUE TITLE
Crash while breaking lan cable

### ISSUE THREAD

**Issue by Nathan1852** [SquidDev-CC/CC-Tweaks#45]
I crashed when I had two cables connected to a Wireless Bridge, one with modem, one without and I broke the cable without modem.

Crash: Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
	at org.squiddev.cctweaks.core.network.modem.BasicModem.findPeripherals(BasicModem.java:140)
	at org.squiddev.cctweaks.blocks.network.TileNetworkedWirelessBridge.func_145845_h(TileNetworkedWirelessBridge.java:93)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by SquidDev** [comment]
Sorry for all these bugs. :frowning:.

This is a really odd bug as nothing should be modifying the map at the same time - we lock on it after all. Also, this is a really hard bug to reproduce, and so actually test. Do you think you could give me a screenshot of the entire setup?

**Comment by Nathan1852** [comment]
No problem, I'm using the beta version and know that I have to expect bugs ;) It's better when I discover them now instead of two weaks after a new release.
I'll edit this comment as soon as I have a screenshot

**Comment by SquidDev** [comment]
I've tried having 4 turtles trying to break and replace cables whilst also sending messages along the cable and attaching and detaching peripherals and I haven't been able to reproduce. Obviously it happens, but I really don't know how to force it to happen.

Wireless bridges, you need to create a data card and then shift right click on it (it should show a message in the chat saying "Settings stored", then right click on other modems to load it from the card. It is a bit like AE's P2P tunnels, but not.

**Comment by Nathan1852** [comment]
I did that, it didn't seem to work :/ Maybe because I was in Creative?

**Comment by SquidDev** [comment]
Shouldn't have anything to do to with it. I'll test.

**Comment by Nathan1852** [comment]
I always got them two times ^^ But getNamesRemote() didn't return anything

**Comment by SquidDev** [comment]
Ahh, just realised why the chat message appears twice. *Doh*.

It works on my machine isn't a great answer so I'm slightly confused. It is worth noting that:
 - The wireless bridge doesn't chunk load - so if you have one in another dimension/a long way away then you'll need to chunk load it somehow.
 - It needs to be connected directly to a computer of a cable - there shouldn't be a modem next to it (though you can have a full block modem next to it).
 - If you press F3+H and get two data cards, then normal right click on both - can you verify that the bottom line of text is the same (it should be a UUID - like `f81d4fae-7dec-11d0-a765-00a0c91e6bf6`).

**Comment by Nathan1852** [comment]
They were 10 blocks away from each other. 
When I shouldn't connect a modem to it, why does it have methods like getNamesRemote, open and transmit?
And yes, the data cards have an uuid each.
And it works when I just put cables next to it and use the card. 
It didn't work because I connected it with a modem, not with only a cable

**Comment by SquidDev** [comment]
It is designed to also double as a modem - so can be connected to a computer directly and so has those additional methods. However when connected via a modem those methods aren't called when searching for more peripherals. I'm going to have to document this better. :sob:...

**Comment by Nathan1852** [comment]
I think a post for it in the github wiki would be really nice, but since this is a beta, it isn't that needed right now

**Comment by SquidDev** [comment]
Hopefully fixed in #34.
