### ISSUE TITLE
Network optimisations

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaks#48]
- [x] ~~Replace set of connections with a more efficient data structure. Ideally we should be able to find connections to/from any node without having to iterate through the list. A `Map<INetworkNode, Set<INetworkNode>>` would work, but it does mean a two way mapping is harder to ensure.~~ Whilst profiling this it doesn't seem too much of a problem. It is less than ideal, but should be OK.
 - [x] Bring back the unit tests. I deleted them in 3bc51af1a10666891fe4d72177e37fa15e373ca0 but it might be worth bringing them back in a different form to ensure that everything works correctly.
 - [x] ~~Optimise the network code. Currently removing a node recreates the entire network. This could be happening several hundred times on a chunk unload.~~ Not really a problem.
 - [x] Cables cache connections
 - [ ] Send packets directly rather than on the update tick.

It might also be worth considering changing the use of `getMetadata` (TileGeneric method) to `getBlockMetadata` (TileEntity method) as this, and the `getBlock` equivalent implement caching.

**Comment by ElvishJerricco** [comment]
I do think having a set of connections is the most efficient way of doing this. It's much better than traversing the entire network multiple times for any change, which is what vanilla CC does.

**Comment by SquidDev** [comment]
The trouble is that it is much harder to then find connections from a node, and so to send a message you end up iterating the connection map once for every node on the network - which isn't optimal.

**Comment by ElvishJerricco** [comment]
I think that operation is rather minimal. The advantages of remembering connections as a set are fairly valuable I think

**Comment by SquidDev** [comment]
You're probably right. I'll profile everything later today to see if there are any hot spots though.

**Comment by ElvishJerricco** [comment]
For instance, in creating new networks when a node is removed, all that needs allocating is the new network objects. The connections get to be transferred from one to the other very efficiently. And especially joining two networks is really efficient this way.

**Comment by SquidDev** [comment]
Looking at OpenComputers, they use `Map<INetworkNode, Set<Connection>>`. I don't want to copy and paste their [network infrastructure](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/server/network/Network.scala), but it is pretty well written.

Also, they've copied my idea of using markdown as an in-game documentation format. :frowning:.
