### ISSUE TITLE
Maven dependencies are wrong.

### ISSUE THREAD

**Issue by ElvishJerricco** [SquidDev-CC/CC-Tweaks#53]
As it is, ComputerCraft is the ONLY compile dependency listed, which is the opposite of what it should be. Maven won't use the ivy repository listed in Gradle to look for dependencies. Using CC-Tweaks' maven repo as a dependency in Gradle won't ever build, and will fail to compile against the various other dependencies.

**Comment by ElvishJerricco** [comment]
I assume it's because of [this line](https://github.com/SquidDev-CC/CC-Tweaks/blob/master/gradle/scripts/upload.gradle#L43)? I imagine that's supposed to be removing the CC dependency, but in reality it's making CC the only dependency.

**Comment by SquidDev** [comment]
It was doing what it was meant to be doing: CC should be the only dependency. However I should just be removing all compile dependencies.

I was trying to ensure the `shade` and `packaged` dependencies never got included.

**Comment by SquidDev** [comment]
Re uploaded, looks like it is fixed.

**Comment by ElvishJerricco** [comment]
But why not declare all the maven dependencies such as the ChickenBones stuff?

**Comment by SquidDev** [comment]
There not 'run-time' dependencies, simply compile time, and so it seems to make more sense to only define the ones to run at minimal functionality.
