### ISSUE TITLE
Messed up Texture

### ISSUE THREAD

**Issue by Nathan1852** [SquidDev-CC/CC-Tweaks#54]
![2015-07-18_14 45 19](https://cloud.githubusercontent.com/assets/5282863/8761652/1d17bcbc-2d5c-11e5-828a-8e7657248573.png)

As can be seen above, the newest CCTweaks has somehow a messed up renderer

**Comment by SquidDev** [comment]
Ok. That is weird. Can you give me a mod list please? I'd say at a guess that I'm forgetting to bind textures or something - though that block has no custom renderer so this is very odd.

**Comment by Nathan1852** [comment]
Here is my complete log: http://puu.sh/j3H6t/0340fb6426.log
All loaded mods should be in there.
Btw, this problem didn't exist in the beta you had before this release

**Comment by SquidDev** [comment]
Curiouser and curiouser. I can't see anything wrong with it on my end - I know this normally works correctly - but I'll double check. You have one ton of mods installed :stuck_out_tongue_winking_eye:.

**Comment by Nathan1852** [comment]
I know  :stuck_out_tongue_winking_eye:
I would have more if my pc couldtake it

**Comment by SquidDev** [comment]
I'm hoping to get version 0.2.1 out in the next week or so, also trying to close #36, so can you test then. I'll reopen and hope for the best if it isn't fixed then.

**Comment by SquidDev** [comment]
@Nathan1852 Can you confirm or deny if this is fixed with [0.2.1](https://github.com/Nathan1852)?

**Comment by Nathan1852** [comment]
Yes, this is fixed in the newest version

**Comment by SquidDev** [comment]
Yeay :tada:!
