### ISSUE TITLE
Modem not turning red when connected

### ISSUE THREAD

**Issue by Nathan1852** [SquidDev-CC/CC-Tweaks#55]
Sorry guys, I have another bug report ;P
The modems in the newest version don't turn red when connected to a peripheral.
I removed CCTweaks and they all turned red, so it is definetly caused by CCTweaks.

![2015-07-19_21 40 09](https://cloud.githubusercontent.com/assets/5282863/8767585/540bb786-2e61-11e5-80e7-8717579c5193.png)

**Comment by SquidDev** [comment]
Sorry to be a pain, but if you connect it and re-log, does it turn red? Also, if you use `rednet.connect(side)` does it turn red then?

Also, can you duplicate this behaviour for multipart modems? (try placing two modems in one block and turn one on).

**Comment by Nathan1852** [comment]
No problem at all :D
I want the problem fixed as fast as you do and know how easy something can go wrong, so...
I'll edit the results into this comment as soon as I have them. 
It should be in about 5 minutes

**Comment by SquidDev** [comment]
Thanks for taking the time to report them! All I can say is 'it works on my machine'!

**Comment by ElvishJerricco** [comment]
I've also observed this but forgot to report it. For me, this is the case with both TileCable modems and multipart modems. I think it was actually turning the wrong part red (the part meant for signifying that rednet has opened a channel)

**Comment by SquidDev** [comment]
So there are several possible causes for this:
 - Forgetting to sync the state change - if it changes after a relog then this is probably the case
 - Not redrawing - this shouldn't occur, but is a possibility

Better test again then.

**Comment by SquidDev** [comment]
Right, goes to try it and it happens first time. *Sigh*

**Comment by Nathan1852** [comment]
Well, this seems a bit messed up.
It sometimes works for me and sometimes doesn't.
It also seems that reloging helps. But not all the times. 
Sometimes it works directly after placing and sometimes it doesn't

**Comment by ElvishJerricco** [comment]
Oh that's brilliant. Love it. I'll take a look at the code in detail when I get back to my laptop.

**Comment by SquidDev** [comment]
@Nathan1852 
> reloging helps. But not all the times. 

Hmmm, it should always help. Odd
@ElvishJerricco It doesn't work yet, I'm copying large potions of my luaj.api project, but there is still lots of work to be done (the test classes don't totally compile yet).

**Comment by Nathan1852** [comment]
It maybe helps all the time. I think i just didn't connect the modems that didn't work after reloging, but I crashed with something unrelated before I could find out...

**Comment by Nathan1852** [comment]
You guys are crazy fast with bugfixes. Thank you for that

**Comment by SquidDev** [comment]
It was only one line. Stupid mistake on my part :facepunch:. I can't reproduce with mutliparts, though I'll have a look tomorrow.

[Here you go](http://maven.bonzodandd.co.uk/org/squiddev/CCTweaks/1.7.10-0.2.1/CCTweaks-1.7.10-0.2.1.jar)
