### ISSUE TITLE
Wireless bridge for Pocket Computers

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaks#56]
Using Peripherals++'s [Pocket computer upgrade](https://github.com/austinv11/PeripheralsPlusPlus/blob/master/src/main/java/com/austinv11/peripheralsplusplus/hooks/IPocketComputerUpgrade.java). We can use the same API format as turtles, but scan the inventory or use the slot to the right or something to find a valid card.

I think the only issue with this is that players do not have an integer position, and so `IWorldPosition` is inaccurate.

**Comment by austinv11** [comment]
If you end up doing this, please feel free to give me feedback about the api! Also, submit a PR to edit [this](https://github.com/austinv11/PeripheralsPlusPlus/blob/documentation/docs/pocket_computer_upgrades/pocket_computer_upgrade_ids.md) as you would for turtle upgrades.

**Comment by SquidDev** [comment]
@austinv11 Do you have a maven repo? Just making mods a dependency using curse downloads is kinda annoying.

**Comment by austinv11** [comment]
I do with collective framework, but I guess I can create a repo for
peripherals++ too

**Comment by SquidDev** [comment]
Ahh, [here](http://jcenter.bintray.com/com/austinv11/collectiveframework/CollectiveFramework/)?

**Comment by austinv11** [comment]
Yup. When I get back home in a few hours I could set up the Peripherals++
one.

**Comment by austinv11** [comment]
Here you are: http://jcenter.bintray.com/com/austinv11/peripheralsplusplus/PeripheralsPlusPlus/

**Comment by SquidDev** [comment]
@austinv11 Thanks! I'm probably being really stupid - but how do you create a pocket computer with a peripheral - I can't find a crafting handler for it.

**Comment by austinv11** [comment]
What do you mean? In game?

**Comment by SquidDev** [comment]
Yeah. I'm probably being stupid.

**Comment by austinv11** [comment]
Just craft a pocket computer with the peripheral of choice, however make sure that it isn't a wireless pocket computer!

**Comment by SquidDev** [comment]
Hmmm, I'll test in a non-dev environment but I can't seem to get it to work. 167 is the latest correct.

---

`Unknown recipe class! com.austinv11.peripheralsplusplus.recipe.ContainerRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter`.
You need to [register your handler](https://github.com/SquidDev-CC/CC-Tweaks/blob/master/src/main/java/org/squiddev/cctweaks/items/ItemComputerUpgrade.java#L131). I know it is odd having to do it twice.

**Comment by austinv11** [comment]
Hm, you may need to add some command line arguments then, particularly this: -Dfml.coreMods.load=com.austinv11.collectiveframework.minecraft.asm.CollectiveFrameworkEarlyTransformerPlugin,com.austinv11.peripheralsplusplus.asm.PeripheralsPlusPlusTransformerPlugin

Although the coremods should be loading since your running pre-compiled versions of the mod

**Comment by SquidDev** [comment]
Its finding the Peripherals++ one, but not CollectiveFramework. You are doing some pretty dark magic in some of the CollectiveFramework classes :stuck_out_tongue_winking_eye:.

**Comment by austinv11** [comment]
Interesting...Gonna need to see why it isn't working with CollectiveFramework, and yes I am ;) I wish some of the hackiness wasn't required but coremods make everything weird.

**Comment by SquidDev** [comment]
So the core mods argument makes your code work. Its now mine which is broken. :tada: :cake:. Thanks!

**Comment by austinv11** [comment]
Yeah.. I have no idea why I have that recipe working like it is. I think I was just too lazy to make an IRecipe. Looks like I should probably change it. Anyways, have fun fixing stuff.

**Comment by SquidDev** [comment]
**Note to self:** Doesn't seem to save the binding.

@austinv11 Collective Framework is fixed now. Thanks!
