### ISSUE TITLE
MCMultipart Support for 1.8.9

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaks#75]
See: https://github.com/amadornes/MCMultiPart

~~Sadly this is only for 1.8.9 - we will have to wait til CC gets updated for that.~~

CC 1.77pr0 has been released.

**Comment by ElvishJerricco** [comment]
Interesting! I might jump back in for this. I'll have to check out the API. I'd love to contribute to that as well

**Comment by SquidDev** [comment]
You'll have to wait a bit - its only for 1.8.8 which CC hasn't updated to yet. :frowning: I'd love your help when the time comes though!

**Comment by ElvishJerricco** [comment]
Yea I know. I can look at the API and maybe do some work on that though.

**Comment by SquidDev** [comment]
CC has been updated to 1.8.9: Hoping to get most of the code working later today. Some things to note though with the new API:
- [The part converter](https://github.com/amadornes/MCMultiPart/blob/1.0.4/src/main/java/mcmultipart/multipart/IPartConverter.java) allows returning multiple parts from one so there is no need for `PartModemWithCableIntermediate`.
- There is also a reverse converter, which means we can revert simple multiparts back into CC cables/modems.
- We will have to use blockstates. Though we can probably hook onto CC's own modem models.

This should also close #36.

**Comment by ElvishJerricco** [comment]
Looks like MCMultiPart could have more potential than FMP. Exciting.

**Comment by SquidDev** [comment]
I think LexManos is considering integrating it with Forge, so it is an official API which is even better: there is pretty much guaranteed continuity for 1.8.9+. This API and blockstates should make the code much nicer & smaller. :smile:

**Comment by ElvishJerricco** [comment]
Fantastic. The FMP code was... Annoying, to say the least.

**Comment by SquidDev** [comment]
Closed in #80
