### ISSUE TITLE
No way to use toolhost?

### ISSUE THREAD

**Issue by JomerDev** [SquidDev-CC/CC-Tweaks#85]
It seems that there is no way in 1.7.10 to use the toolhost.
I've equipped it on a turtle, but it doesn't return any functions to call with perphetal.getMethods()

I'm on the latest CCTweaks version (3.0.1)

Edit: I tried the Advanced toolhost and it works fine
(Although a bit ingame documentation would be nice)

Edit2: Oh, I figured it out. There are no special commands on the tool host, only on the avanced one.
This shows the need for some documentation ;)

**Comment by SquidDev** [comment]
If you have NEI installed and press "r" or "u" there should be some very basic documentation, but it does need improvement (and copying over to the wiki).

**Comment by JomerDev** [comment]
Btw, I would love it if the advanced toolhost could also .use() items by leftclicking. Since some items neither attack nor dig

**Comment by SquidDev** [comment]
> Btw, I would love it if the advanced toolhost could also .use() items by leftclicking. Since some items neither attack nor dig

I've had a look at this and can't find a way items can do this: the only left click actions are `onLeftClickEntity` and digging. Could you give an example of a mod that does this?

**Comment by JomerDev** [comment]
I tried to let the Turtle use the PortalGun. It can create one Portal (right click) but not the other (left click)

(Btw, is there any chance that tools like Immersive Engineerings Hammer can actually 'create' the Multiblocks with a .use() like when one uses the Hammer themself)

**Comment by SquidDev** [comment]
Ahh: portal gun. I seem to remember OpenComputers has some custom handling just for it. I'll see what I can do. Haven't really played with Immersive Engineering: I'll have a look.

**Comment by SquidDev** [comment]
The IE hammer appears to work for me (I only tested on the coke oven). Is there a multiblock it doesn't work on?

---

Just had a look at portal gun: it uses client side checks rather than built in minecraft methods. I'll have a think about the best way to add integration for this.

**Comment by JomerDev** [comment]
I tested the turtle with a hammer on an excavator and it didn't work

It would be so great if you could get this working

**Comment by SquidDev** [comment]
I've added portal gun integration (and an API to add other mods if the need arises) and fixed the issue with the IE hammer. A work around you can use before I release this fix is to move the turtle one block away before using the item.

**Comment by JomerDev** [comment]
Thank you for your fast fixes/fast implementing of new features. It makes this mod one of my favourites
