### ISSUE TITLE
LuaJ graphic problems

### ISSUE THREAD

**Issue by JomerDev** [SquidDev-CC/CC-Tweaks#86]
After I enabled LuaJs compiling to Java bytecode, I got some wierd graphics problems:
![2016-02-09_17 27 42](https://cloud.githubusercontent.com/assets/5282863/12928227/8bf552b8-cf6c-11e5-8d72-f6d5c86a1621.png)

The text I type in doesn't show up, and the suggestions for what to type are messed up
Text I print out with print() is fine though

**Comment by SquidDev** [comment]
I'm moving this to the LuaJC repo as it is a bug there. I'll post something here once I've actually fixed it. It appeared between luaj.luajc 1.0.3 and 1.0.4 (CCTweaks 0.3 and 0.3.0.1).

**Comment by SquidDev** [comment]
Fixed in 0.3.0.2
