### ISSUE TITLE
When loading the game, it crashes.

### ISSUE THREAD

**Issue by kd8lvt** [SquidDev-CC/CC-Tweaks#87]
Only just recently added your mod, and the [crash log](http://pastebin.com/vFGbV9wG) is yelling about CCTweaks having a "ClassNotDefFound" error. Here is my [modlist](http://pastebin.com/TNGeEYHV) It may just be me missing a coremod (I would have it if I had known about one) Hope this issue gets resolved soon so i can get back on modpack dev-ing.
Thanks!
    ~Kd
(PS I hope you don't mind if I use the mod in a pack once the issue gets resolved, it seems like a great mod. And yes, I see the MIT lisence over there, I just like to ask ;D)

**Comment by SquidDev** [comment]
Ouch. A temporary fix would be to add [MCMultipart](http://minecraft.curseforge.com/projects/mcmultipart). 

I'll have a look now. Sorry :frowning:.

**Edit:** Feel free to use it in your modpack - I love it when people use this mod :smile:.

**Comment by kd8lvt** [comment]
Thanks for the quick response and hotfix solution, looking forward to using the mod :)

**Comment by SquidDev** [comment]
Fixed in 0.3.0.2
