### ISSUE TITLE
Wireless bridge changes

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/CC-Tweaks#91]
[From this post](http://www.computercraft.info/forums2/index.php?/topic/21987-mc-171018189-cc-tweaks/page__view__findpost__p__246309)

> Wireless Bridge block: should use wireless channels to connect wired networks. And programmed by computers. Data card is bad idea. Now it's magic. IMHO ofc.
> 
> Not sure what to do about the wireless bridge. I like the data card as it allows a bit more security but it also is a bit clunky. Whilst using wireless channels isn't really possible due to CC internals, using the same method would work. I'll put something on my issue tracker and see what others think.

I'd probably add a `setChannel` method to wireless bridges. This would replace the data card, though it would still work.

---

I'm putting this out here for others to comment on what they think.

**Comment by JomerDev** [comment]
I think that a setChannel method is a nice addition to the wireless bridge
