### ISSUE TITLE
Modem bridge not working across dimensions

### ISSUE THREAD

**Issue by Julyanvdham** [SquidDev-CC/CC-Tweaks#96]
The Wireless Bridge does not work across dimensions.
I am using CCTweaks version 0.3.2 and computercraft version 1.75

**Comment by SquidDev** [comment]
Thanks for the report! Just a couple of things to check:
- How are you binding the two bridges: do they work in the same dimension?
- Are both ends chunk loaded?

I've tested this quite recently and it all seemed to work so this is odd. Also, could put your log on pastebin: this allows me to check that all the patches are being applied correctly and see which mods you have.

**Comment by Julyanvdham** [comment]
the 2 blocks are placed like this: [bridge][network cable][wired modem][advanced computer] and connected via the data card item

and yes, both ends are chunkloaded

**Comment by Julyanvdham** [comment]
Could you explain how to set them up?

**Comment by SquidDev** [comment]
That should work correctly. I'll have a look. If you shift-right click one with a data card, then right click the other then they should be bound. You can also use `openRemote(channelId)` on both bridges to open a connection.

**Comment by Julyanvdham** [comment]
Updating forge has resolved the issue for me

**Comment by SquidDev** [comment]
Hmmmm, very odd. I'm going to close this as I it seems to work on my end and you've managed to fix it.
