### ISSUE TITLE
Remote inventories not seeming to work

### ISSUE THREAD

**Issue by Selim042** [SquidDev-CC/CC-Tweaks#98]
I might be derping this up, but I have a wired modem block, connected to an iron chest, a turtle, and vanilla chest.  I am attempting to call `iron.pushItemRemote("chest_0",1)` but it is returning 

> lua:1: Parameter 1 value not set

**Comment by SquidDev** [comment]
Which version of CC, CCTweaks and OpenPeripheral are you running? Also can I have your log? Thanks!

**Comment by Selim042** [comment]
Oh, sorry about that, forgot versions:
Minecraft: 1.7.10
ComputerCraft: 1.75
CCTweaks: 0.3.2
OpenPeripheralCore: 1.3
OpenPeripheralIntegration: 0.5
OpenPeripheralAddons: 0.5.1

How much of the log do you need?  Just around when I tried the function, or the whole thing?

Oh yea, not that it should matter, but this is on a server.

**Comment by SquidDev** [comment]
Fixed in 39740a48a2689e8b3aa6b54380a711192094974d. I've pushed it but GitHub is derping.
