### ISSUE TITLE
Networked Pocket Computer not seeing Bridge

### ISSUE THREAD

**Issue by Selim042** [SquidDev-CC/CC-Tweaks#99]
I attached a Wireless Bridge to an Advanced Pocket Computer, though the peripheral API does not seem to see it as a peripheral.  I tried `peripheral.getNames()`, that returned

> {}

and `peripheral.getType("back")` returned

> nil

**Comment by Selim042** [comment]
Ok, that was odd, apparently the computers just need to sit in a chest for a min?  Sorry about that.

**Comment by SquidDev** [comment]
I thought I fixed this in the latest version: It only registered once the computer had been turned off and on again: hence putting it in the chest fixed this. Which version are you running?

**Comment by Selim042** [comment]
CCTweaks 0.3.2

I had tried rebooting the PC repeatedly and that hadn't done anything, so I assume it has to be a full shutdown?

**Comment by SquidDev** [comment]
It has to be a full "destroy the computer instance" shutdown. `shutdown` or `reboot` don't do that.

Sadly as this is 1.7.10 I can't do anything about this: I'm using [Peripherals++'s](https://github.com/austinv11/PeripheralsPlusPlus/) pocket upgrades so their code is at fault. I'll file an issue there.
